name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  create-new-release:
    name: Create new APK release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build flutter web app
        run: flutter build apk --release
