name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  create-new-release:
    name: Create new APK release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get the last tag
        run: |
          git fetch --tags
          OLD_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag is : ${OLD_TAG}"
          echo "old_tag=${OLD_TAG}" >> $GITHUB_ENV

      - name: Build flutter web app
        run: flutter build apk --release

      - name: Create new tag
        run: |
          NEW_TAG=v$(TZ=Europe/Paris date +'%d.%m.%Y-%Hh%M')
          echo "Creating new tag : ${NEW_TAG}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "new_tag=${NEW_TAG}" >> $GITHUB_ENV

      - name: Get commit messages
        run: |
          git log ${{ env.old_tag }}..HEAD --pretty=format:"[%h](https://github.com/esgi-challenge/mobile/commit/%H): %s" > commits.txt
          COMMITS=$(cat commits.txt)
          echo "List of all the new commits : ${COMMITS}"
          echo "commits=${COMMITS}" >> $GITHUB_ENV

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.new_tag }} \
            build/app/outputs/flutter-apk/app-release.apk \
            --title "Release ${{ env.new_tag }}" \
            --notes "${{ env.commits }}"
