name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - maste

jobs:
  create-new-release:
    name: Create new APK release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get the last tag
        id: last-tag
        run: |
          git fetch --tags
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Build flutter web app
        run: flutter build apk --release


      - name: Create new tag
        id: new-tag
        run: |
          NEW_TAG=v$(date +'%d.%m.%Y-%Hh%M')
          echo "NEW_TAG=${NEW_TAG}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "::set-output name=new_tag::$NEW_TAG"
